/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DreamService } from "../dream.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DreamCreateInput } from "./DreamCreateInput";
import { Dream } from "./Dream";
import { DreamFindManyArgs } from "./DreamFindManyArgs";
import { DreamWhereUniqueInput } from "./DreamWhereUniqueInput";
import { DreamUpdateInput } from "./DreamUpdateInput";
import { TagFindManyArgs } from "../../tag/base/TagFindManyArgs";
import { Tag } from "../../tag/base/Tag";
import { TagWhereUniqueInput } from "../../tag/base/TagWhereUniqueInput";
import { DreamWhereInput } from "./DreamWhereInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DreamControllerBase {
  constructor(
    protected readonly service: DreamService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Dream })
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDream(@common.Body() data: DreamCreateInput): Promise<Dream> {
    return await this.service.createDream({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        image: true,
        link: true,
        query: true,
        response: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Dream] })
  @ApiNestedQuery(DreamFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dreams(@common.Req() request: Request): Promise<Dream[]> {
    const args = plainToClass(DreamFindManyArgs, request.query);
    return this.service.dreams({
      ...args,
      select: {
        createdAt: true,
        id: true,
        image: true,
        link: true,
        query: true,
        response: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Dream })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dream(
    @common.Param() params: DreamWhereUniqueInput
  ): Promise<Dream | null> {
    const result = await this.service.dream({
      where: params,
      select: {
        createdAt: true,
        id: true,
        image: true,
        link: true,
        query: true,
        response: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Dream })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDream(
    @common.Param() params: DreamWhereUniqueInput,
    @common.Body() data: DreamUpdateInput
  ): Promise<Dream | null> {
    try {
      return await this.service.updateDream({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          image: true,
          link: true,
          query: true,
          response: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Dream })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDream(
    @common.Param() params: DreamWhereUniqueInput
  ): Promise<Dream | null> {
    try {
      return await this.service.deleteDream({
        where: params,
        select: {
          createdAt: true,
          id: true,
          image: true,
          link: true,
          query: true,
          response: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/tags")
  @ApiNestedQuery(TagFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Tag",
    action: "read",
    possession: "any",
  })
  async findTags(
    @common.Req() request: Request,
    @common.Param() params: DreamWhereUniqueInput
  ): Promise<Tag[]> {
    const query = plainToClass(TagFindManyArgs, request.query);
    const results = await this.service.findTags(params.id, {
      ...query,
      select: {
        createdAt: true,

        dream: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        parent: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tags")
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "update",
    possession: "any",
  })
  async connectTags(
    @common.Param() params: DreamWhereUniqueInput,
    @common.Body() body: TagWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tags: {
        connect: body,
      },
    };
    await this.service.updateDream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tags")
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "update",
    possession: "any",
  })
  async updateTags(
    @common.Param() params: DreamWhereUniqueInput,
    @common.Body() body: TagWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tags: {
        set: body,
      },
    };
    await this.service.updateDream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tags")
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "update",
    possession: "any",
  })
  async disconnectTags(
    @common.Param() params: DreamWhereUniqueInput,
    @common.Body() body: TagWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tags: {
        disconnect: body,
      },
    };
    await this.service.updateDream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/dreams/createFromAPI")
  @swagger.ApiOkResponse({
    type: Dream,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async CreateDreamWithApi(
    @common.Body()
    body: DreamWhereInput
  ): Promise<Dream> {
    return this.service.CreateDreamWithApi(body);
  }

  @common.Get("/dreams")
  @swagger.ApiOkResponse({
    type: Dream,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetDreamsList(
    @common.Body()
    body: DreamWhereInput
  ): Promise<Dream[]> {
    return this.service.GetDreamsList(body);
  }
}
