/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Dream } from "./Dream";
import { DreamCountArgs } from "./DreamCountArgs";
import { DreamFindManyArgs } from "./DreamFindManyArgs";
import { DreamFindUniqueArgs } from "./DreamFindUniqueArgs";
import { CreateDreamArgs } from "./CreateDreamArgs";
import { UpdateDreamArgs } from "./UpdateDreamArgs";
import { DeleteDreamArgs } from "./DeleteDreamArgs";
import { TagFindManyArgs } from "../../tag/base/TagFindManyArgs";
import { Tag } from "../../tag/base/Tag";
import { User } from "../../user/base/User";
import { DreamCreateInput } from "./DreamCreateInput";
import { DreamWhereInput } from "./DreamWhereInput";
import { DreamService } from "../dream.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Dream)
export class DreamResolverBase {
  constructor(
    protected readonly service: DreamService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "read",
    possession: "any",
  })
  async _dreamsMeta(
    @graphql.Args() args: DreamCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Dream])
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "read",
    possession: "any",
  })
  async dreams(@graphql.Args() args: DreamFindManyArgs): Promise<Dream[]> {
    return this.service.dreams(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Dream, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "read",
    possession: "own",
  })
  async dream(
    @graphql.Args() args: DreamFindUniqueArgs
  ): Promise<Dream | null> {
    const result = await this.service.dream(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Dream)
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "create",
    possession: "any",
  })
  async createDream(@graphql.Args() args: CreateDreamArgs): Promise<Dream> {
    return await this.service.createDream({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Dream)
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "update",
    possession: "any",
  })
  async updateDream(
    @graphql.Args() args: UpdateDreamArgs
  ): Promise<Dream | null> {
    try {
      return await this.service.updateDream({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Dream)
  @nestAccessControl.UseRoles({
    resource: "Dream",
    action: "delete",
    possession: "any",
  })
  async deleteDream(
    @graphql.Args() args: DeleteDreamArgs
  ): Promise<Dream | null> {
    try {
      return await this.service.deleteDream(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Tag], { name: "tags" })
  @nestAccessControl.UseRoles({
    resource: "Tag",
    action: "read",
    possession: "any",
  })
  async findTags(
    @graphql.Parent() parent: Dream,
    @graphql.Args() args: TagFindManyArgs
  ): Promise<Tag[]> {
    const results = await this.service.findTags(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Dream): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Dream)
  async CreateDreamWithApi(
    @graphql.Args()
    args: DreamCreateInput
  ): Promise<Dream> {
    return this.service.CreateDreamWithApi(args);
  }

  @graphql.Query(() => [Dream])
  async GetDreamsList(
    @graphql.Args()
    args: DreamWhereInput
  ): Promise<Dream[]> {
    return this.service.GetDreamsList(args);
  }
}
